const expect = require('chakram').expect;

var success = {
  "id": 79703,
  "name": "ollingStuff",
  "createdDate": "2017-11-22T17:28:55Z",
  "token": "uyQTU4kEciptZowql8y3athFDc2eL9mz5+uRgjRvA0s=",
  "element": {
    "id": 148,
    "name": "HubSpot CRM",
    "hookName": "HubSpotCRM",
    "key": "hubspotcrm",
    "description": "HubSpot is an inbound marketing software platform that helps companies attract visitors, convert leads, and close customers.",
    "image": "elements/provider_hubspot.png",
    "active": true,
    "deleted": false,
    "typeOauth": true,
    "trialAccount": false,
    "configDescription": "If you do not have a HubSpot account, you can create one at <a href=\"http://www.hubspot.com\" target=\"_blank\">HubSpot Signup</a>",
    "transformationsEnabled": true,
    "bulkDownloadEnabled": true,
    "bulkUploadEnabled": true,
    "cloneable": false,
    "extendable": true,
    "beta": false,
    "authentication": {
      "type": "oauth2"
    },
    "extended": false,
    "hub": "crm",
    "protocolType": "http",
    "parameters": [],
    "private": false
  },
  "elementId": 148,
  "tags": [
    "ollingStuff"
  ],
  "provisionInteractions": [],
  "valid": true,
  "disabled": false,
  "maxCacheSize": 0,
  "cacheTimeToLive": 0,
  "configuration": {
    "base.url": "https://api.hubapi.com",
    "event.notification.subscription.id": "89860",
    "hubspot.deals.properties": "hs_analytics_source,hs_analytics_source_data_1,hs_analytics_source_data_2,hs_campaign,hs_lastmodifieddate,hubspot_owner_assigneddate,dealname,amount,dealstage,pipeline,closedate,createdate,engagements_last_meeting_booked,engagements_last_meeting_booked_campaign,engagements_last_meeting_booked_medium,engagements_last_meeting_booked_source,hubspot_owner_id,notes_last_contacted,notes_last_updated,notes_next_activity_date,num_contacted_notes,num_notes,hs_createdate,hubspot_team_id,dealtype,description,num_associated_contacts,closed_lost_reason,closed_won_reason",
    "create.bulk.properties": "false",
    "authentication.type": "oauth2",
    "event.vendor.type": "polling",
    "hubspot.contacts.properties": "firstname,lastname,lastmodifieddate,createdate",
    "filter.response.nulls": "true",
    "hubspot.companies.properties": "about_us,facebookfans,first_conversion_date,first_conversion_event_name,first_deal_created_date,founded_year,hs_analytics_first_timestamp,hs_analytics_first_visit_timestamp,hs_analytics_last_timestamp,hs_analytics_last_visit_timestamp,hs_analytics_num_page_views,hs_analytics_num_visits,hs_analytics_source,hs_analytics_source_data_1,hs_analytics_source_data_2,hs_lastmodifieddate,hubspot_owner_assigneddate,is_public,num_associated_contacts,num_associated_deals,num_conversion_events,recent_conversion_date,recent_conversion_event_name,recent_deal_amount,recent_deal_close_date,timezone,total_money_raised,total_revenue,name,twitterhandle,phone,twitterbio,twitterfollowers,address,address2,facebook_company_page,city,linkedin_company_page,linkedinbio,state,googleplus_page,engagements_last_meeting_booked,engagements_last_meeting_booked_campaign,engagements_last_meeting_booked_medium,engagements_last_meeting_booked_source,hubspot_owner_id,notes_last_contacted,notes_last_updated,notes_next_activity_date,num_contacted_notes,num_notes,zip,country,hubspot_team_id,website,domain,numberofemployees,annualrevenue,lifecyclestage,hs_avatar_filemanager_key,hs_lead_status,hs_parent_company_id,type,description,hs_num_child_companies,hubspotscore,createdate,closedate,first_contact_createdate,days_to_close",
    "pagination.type": "offset",
    "oauth.callback.url": "https://auth.cloudelements.io/oauth",
    "event.notification.signature.key": null,
    "oauth.user.refresh_token": "669c0558-51cf-49c9-b23b-23deb4791209",
    "event.poller.urls": "contacts\nopportunities\naccounts",
    "hubspot.webhook.workflow.id": null,
    "oauth.user.refresh_interval": "21600",
    "oauth.api.key": "********",
    "app_id": null,
    "event.notification.enabled": "true",
    "oauth.api.secret": "********",
    "pagination.max": "100",
    "user_portal_id": null,
    "oauth.scope": "contacts timeline files",
    "oauth.user.token": "CPq1wLD-KxICXwcY25_vASCF0bEBKPWrAjIZAGemUHBlu5a014_IHgc_TfVVB4mNjY4dLA",
    "user_email_address": null,
    "event.poller.refresh_interval": "1",
    "event.notification.callback.url": "https://knappkeith.pythonanywhere.com/request/stuffs/",
    "user_id": null,
    "hubspot.authorization.apikey": null,
    "oauth.user.refresh_time": "1511371736106",
    "event.poller.configuration": "{\"accounts\": {\"url\": \"/hubs/crm/accounts?where=lastmodifieddate='${date}'\",\"idField\": \"companyId\",\"filterByUpdatedDate\": true,\"datesConfiguration\": {\"updatedDateField\": \"properties.hs_lastmodifieddate\",\"updatedDateFormat\": \"milliseconds\",\"createdDateField\": \"properties.createdate\",\"createdDateFormat\": \"milliseconds\"},\"createdCheckTolerance\": 10},\"contacts\": {\"url\": \"/hubs/crm/contacts?where=lastmodifieddate='${date}'\",\"idField\": \"vid\",\"filterByUpdatedDate\": true,\"datesConfiguration\": {\"updatedDateField\": \"properties.lastmodifieddate\",\"updatedDateFormat\": \"milliseconds\",\"createdDateField\": \"properties.createdate\",\"createdDateFormat\": \"milliseconds\"},\"createdCheckTolerance\": 10},\"opportunities\": {\"url\": \"/hubs/crm/opportunities?where=lastmodifieddate='${date}'\",\"idField\": \"dealId\",\"filterByUpdatedDate\": true,\"datesConfiguration\": {\"updatedDateField\": \"properties.hs_lastmodifieddate\",\"updatedDateFormat\": \"milliseconds\",\"createdDateField\": \"properties.createdate\",\"createdDateFormat\": \"milliseconds\"},\"createdCheckTolerance\": 10}}"
  },
  "eventsEnabled": true,
  "eventsNotificationCallbackUrl": "https://knappkeith.pythonanywhere.com/request/stuffs/",
  "subscriptionId": 89860,
  "traceLoggingEnabled": false,
  "cachingEnabled": false,
  "externalAuthentication": "none",
  "user": {
    "id": 5805,
    "emailAddress": "churros@churros.com",
    "firstName": "Churros",
    "lastName": "Tests"
  }
}

let fail = { id: 79704,
  name: 'churros-instance',
  createdDate: '2017-11-22T17:35:43Z',
  token: 'dO4uSqp6khfuhis9+RYpWwhaUbL7MmNNq2Lpvfjz6+Q=',
  element:
   { id: 148,
     name: 'HubSpot CRM',
     hookName: 'HubSpotCRM',
     key: 'hubspotcrm',
     description: 'HubSpot is an inbound marketing software platform that helps companies attract visitors, convert leads, and close customers.',
     image: 'elements/provider_hubspot.png',
     active: true,
     deleted: false,
     typeOauth: true,
     trialAccount: false,
     configDescription: 'If you do not have a HubSpot account, you can create one at <a href="http://www.hubspot.com" target="_blank">HubSpot Signup</a>',
     configuration:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     objects: [],
     transformationsEnabled: true,
     bulkDownloadEnabled: true,
     bulkUploadEnabled: true,
     cloneable: false,
     extendable: true,
     beta: false,
     authentication: { type: 'oauth2' },
     hooks: [],
     extended: false,
     hub: 'crm',
     protocolType: 'http',
     parameters: [],
     private: false },
  elementId: 148,
  provisionInteractions: [],
  valid: true,
  disabled: false,
  maxCacheSize: 0,
  cacheTimeToLive: 0,
  configuration:
   { 'base.url': 'https://api.hubapi.com',
     'event.notification.subscription.id': '89864',
     'hubspot.deals.properties': 'hs_analytics_source,hs_analytics_source_data_1,hs_analytics_source_data_2,hs_campaign,hs_lastmodifieddate,hubspot_owner_assigneddate,dealname,amount,dealstage,pipeline,closedate,createdate,engagements_last_meeting_booked,engagements_last_meeting_booked_campaign,engagements_last_meeting_booked_medium,engagements_last_meeting_booked_source,hubspot_owner_id,notes_last_contacted,notes_last_updated,notes_next_activity_date,num_contacted_notes,num_notes,hs_createdate,hubspot_team_id,dealtype,description,num_associated_contacts,closed_lost_reason,closed_won_reason',
     'create.bulk.properties': 'true',
     'authentication.type': 'oauth2',
     'event.vendor.type': 'polling',
     'hubspot.contacts.properties': 'firstname,lastname,lastmodifieddate,createdate',
     'filter.response.nulls': 'true',
     'hubspot.companies.properties': 'about_us,facebookfans,first_conversion_date,first_conversion_event_name,first_deal_created_date,founded_year,hs_analytics_first_timestamp,hs_analytics_first_visit_timestamp,hs_analytics_last_timestamp,hs_analytics_last_visit_timestamp,hs_analytics_num_page_views,hs_analytics_num_visits,hs_analytics_source,hs_analytics_source_data_1,hs_analytics_source_data_2,hs_lastmodifieddate,hubspot_owner_assigneddate,is_public,num_associated_contacts,num_associated_deals,num_conversion_events,recent_conversion_date,recent_conversion_event_name,recent_deal_amount,recent_deal_close_date,timezone,total_money_raised,total_revenue,name,twitterhandle,phone,twitterbio,twitterfollowers,address,address2,facebook_company_page,city,linkedin_company_page,linkedinbio,state,googleplus_page,engagements_last_meeting_booked,engagements_last_meeting_booked_campaign,engagements_last_meeting_booked_medium,engagements_last_meeting_booked_source,hubspot_owner_id,notes_last_contacted,notes_last_updated,notes_next_activity_date,num_contacted_notes,num_notes,zip,country,hubspot_team_id,website,domain,numberofemployees,annualrevenue,lifecyclestage,hs_avatar_filemanager_key,hs_lead_status,hs_parent_company_id,type,description,hs_num_child_companies,hubspotscore,createdate,closedate,first_contact_createdate,days_to_close',
     'pagination.type': 'offset',
     'oauth.callback.url': 'https://httpbin.org/get',
     'event.notification.signature.key': null,
     'oauth.user.refresh_token': '6e2899ec-89af-434e-8593-cf011bb378fc',
     'event.poller.urls': 'accounts\ncontacts\nopportunities',
     'hubspot.webhook.workflow.id': null,
     'oauth.user.refresh_interval': '21600',
     'oauth.api.key': '********',
     app_id: null,
     'event.notification.enabled': 'true',
     'oauth.api.secret': '********',
     'pagination.max': '100',
     user_portal_id: null,
     'oauth.scope': 'contacts',
     'oauth.user.token': 'CNCi2bD-KxICXwcY25_vASCF0bEBKMf2AjIZAGemUHDJlWZpgkH1g92Rj2mexb0WcCLUEw',
     user_email_address: null,
     'event.poller.refresh_interval': '1',
     'event.notification.callback.url': 'https://knappkeith.pythonanywhere.com/request/ting/',
     user_id: null,
     'hubspot.authorization.apikey': null,
     'oauth.user.refresh_time': '1511372143231',
     'event.poller.configuration': '{"accounts": {"url": "/hubs/crm/accounts?where=lastmodifieddate=\'${date}\'","idField": "companyId","filterByUpdatedDate": true,"datesConfiguration": {"updatedDateField": "properties.hs_lastmodifieddate","updatedDateFormat": "milliseconds","createdDateField": "properties.createdate","createdDateFormat": "milliseconds"},"createdCheckTolerance": 10},"contacts": {"url": "/hubs/crm/contacts?where=lastmodifieddate=\'${date}\'","idField": "vid","filterByUpdatedDate": true,"datesConfiguration": {"updatedDateField": "properties.lastmodifieddate","updatedDateFormat": "milliseconds","createdDateField": "properties.createdate","createdDateFormat": "milliseconds"},"createdCheckTolerance": 10},"opportunities": {"url": "/hubs/crm/opportunities?where=lastmodifieddate=\'${date}\'","idField": "dealId","filterByUpdatedDate": true,"datesConfiguration": {"updatedDateField": "properties.hs_lastmodifieddate","updatedDateFormat": "milliseconds","createdDateField": "properties.createdate","createdDateFormat": "milliseconds"},"createdCheckTolerance": 10}}' },
  transformationData:
   [ { objectName: 'leads', vendorName: 'leads' },
     { objectName: 'activities', vendorName: 'engagements' },
     { objectName: 'owners', vendorName: 'owners' },
     { objectName: 'accounts', vendorName: 'companies' },
     { objectName: 'opportunities', vendorName: 'deals' },
     { objectName: 'contacts', vendorName: 'contacts' } ],
  eventsEnabled: true,
  eventsNotificationCallbackUrl: 'https://knappkeith.pythonanywhere.com/request/ting/',
  subscriptionId: 89864,
  traceLoggingEnabled: false,
  cachingEnabled: false,
  externalAuthentication: 'none',
  user:
   { id: 5805,
     emailAddress: 'churros@churros.com',
     firstName: 'Churros',
     lastName: 'Tests' } }

it('word', () => expect(fail).to.deep.equal(success));
