'use strict';

const suite = require('core/suite');
const tools = require('core/tools');
const billPaymentsPayload = require('./assets/bill-payments');
const billsPayload = require('./assets/bills');
const creditMemosPayload = require('./assets/credit-memos');
const creditTermsPayload = tools.requirePayload(`${__dirname}/assets/credit-terms.json`);
const customersPayload = tools.requirePayload(`${__dirname}/assets/customers.json`);
const employeesPayload = tools.requirePayload(`${__dirname}/assets/employees.json`);
const invoicesPayload = tools.requirePayload(`${__dirname}/assets/invoices.json`);
const journalEntriesPayload = tools.requirePayload(`${__dirname}/assets/journal-entries.json`);
const ledgerAccountsPayload = tools.requirePayload(`${__dirname}/assets/ledger-accounts.json`);
const paymentMethodsPayload = tools.requirePayload(`${__dirname}/assets/payment-methods.json`);
const paymentsPayload = require('./assets/payments');
const productsPayload = tools.requirePayload(`${__dirname}/assets/products.json`);
const purchaseOrdersPayload = require('./assets/purchase-orders');
const salesReceiptsPayload = require('./assets/sales-receipts');
const timeActivitiesPayload = require('./assets/time-activities');
const vendorCreditsPayload = require('./assets/vendor-credits');
const vendorPayload = tools.requirePayload(`${__dirname}/assets/vendor.json`);

suite.forElement('finance', 'polling', null, (test) => {
  test.withApi('/hubs/finance/bill-payments').should.supportPolling(billPaymentsPayload, 'bill-payments');
  test.withApi('/hubs/finance/bills').should.supportPolling(billsPayload, 'bills');
  test.withApi('/hubs/finance/credit-memos').should.supportPolling(creditMemosPayload, 'credit-memos');
  test.withApi('/hubs/finance/credit-terms').should.supportPolling(creditTermsPayload, 'credit-terms');
  test.withApi('/hubs/finance/customers').should.supportPolling(customersPayload, 'customers');
  test.withApi('/hubs/finance/employees').should.supportPolling(employeesPayload, 'employees');
  test.withApi('/hubs/finance/invoices').should.supportPolling(invoicesPayload, 'invoices');
  test.withApi('/hubs/finance/journal-entries').should.supportPolling(journalEntriesPayload, 'journal-entries');
  test.withApi('/hubs/finance/ledger-accounts').should.supportPolling(ledgerAccountsPayload, 'ledger-accounts');
  test.withApi('/hubs/finance/payment-methods').should.supportPolling(paymentMethodsPayload, 'payment-methods');
  test.withApi('/hubs/finance/payments').should.supportPolling(paymentsPayload, 'payments');
  test.withApi('/hubs/finance/products').should.supportPolling(productsPayload, 'products');
  test.withApi('/hubs/finance/purchase-orders').should.supportPolling(purchaseOrdersPayload, 'purchase-orders');
  test.withApi('/hubs/finance/sales-receipts').should.supportPolling(salesReceiptsPayload, 'sales-receipts');
  test.withApi('/hubs/finance/time-activities').should.supportPolling(timeActivitiesPayload, 'time-activities');
  test.withApi('/hubs/finance/vendor-credits').should.supportPolling(vendorCreditsPayload, 'vendor-credits');
  test.withApi('/hubs/finance/vendor').should.supportPolling(vendorPayload, 'vendors');
});
